version: "3.3"

services:
  web:
    build: py
    command: python app.py
    ports:
      - "80:5000"
    depends_on:
      - db

  db:
    image: mongo
    volumes:
        - ./db/data_dump:/data/db
        - ./db/init:/docker-entrypoint-initdb.d
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}
